blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Community
    url: https://discord.gg/kqNCe2D
    about: Join the Official Homebridge Discord community and ask your questions in the #homepod-radio channel
