name: ❓ Support Request
description: Need help?
labels: [question]

body:
  - type: markdown
    attributes:
      value: |
        Please read the following before you start filling out this form:

        * Support via GitHub issues is limited. You may find it more beneficial ask questions on the [Homebridge Discord](https://discord.gg/kqNCe2D) or [Reddit](https://www.reddit.com/r/homebridge/) communities instead.
        * Search through existing issues (resolved or open) which might provide a solution to your problem already.
        * Aim to find a descriptive and precise title for your support request.

  - type: textarea
    id: describe-your-problem
    attributes:
      label: Describe Your Problem
      description: |
        Please A clear and concise description of your current problem. Be sure to include:

        * What is happening?
        * What do you expect to happen?
        * Clear steps explaining how to reproduce the problem.
      placeholder: |
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide the relevant logs showing the error that occurred.

        * Keep this short. Do not paste in hundreds of lines repeating the same error.
        * Show the logs from the service being restarted until the error occurs.
    validations:
      required: false

  - type: textarea
    id: json-config
    attributes:
      label: Plugin Config
      render: JSON
      description: |
        If relevant to your bug report, please include your Virtual Accessories For Homebridge config (`config.json`).

        * If you're unsure if the config is relevant, please include it.
        * Be sure to **remove any sensitive information (passwords, tokens, etc.).**
    validations:
      required: false

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
    validations:
      required: true

  - type: input
    id: homebridge-ui-version
    attributes:
      label: Homebridge UI Version
    validations:
      required: true

  - type: input
    id: homebridge-version
    attributes:
      label: Homebridge Version
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: |
        We only accept bug reports for systems running even numbered versions of Node.js. See [this link](https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js) for more information.
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Raspbian
        - Ubuntu
        - macOS
        - Windows
        - Docker
      description: |
        If your operating system is not listed, please provide it in the support description.
    validations:
      required: true
