# This is a manually triggered workfow to test discord-webhooks workflow

name: Test Discord Webhooks

# Controls when the workflow will run
on:
  workflow_dispatch

jobs:
  post-test-release-to-discord:
    name: Discord Webhooks

    uses: petro-kushchak/homebridge-homepod-radio/.github/workflows/discord-webhooks.yml@latest
    with:
      title: Test
      description: |
        Version `Test`
      url: 'https://github.com/petro-kushchak/homebridge-homepod-radio/releases/tag/v${{ needs.publish.outputs.NPM_VERSION }}'
    secrets:
      # DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1358459073921814710/g8q8b1KWAKtltvZzAojOvwVBe6FzZGettnIHOx_K8BI-SJCHaQBxJt7JyUiFKAPHnIJH'
